# NUMPY - 1° abrir a documentação

# NUMPY - 2° Qual a diferença do array NUMPY para list in python

In [7]:
import numpy as np
num_elementos = 1000000
#lista_elementos = []
#for x in range(num_elementos):
#  lista_elementos.append(x)
#  print(lista_elementos[-1])
array_elementos = np.arange(num_elementos)
print(array_elementos[-1])


999999


# NUMPY - 3° criação de arryas em nunpy

In [30]:
import numpy as np
array_teste = np.array([0,1,2,3,4,5,6,7,8,9])
print(f'criação de array numpy utilizando o método .array:\n{array_teste}\n')
print(f'criação de array numpy utilizando o método .ones:\n{np.ones([10])}\n')
print(f'criação de array numpy utilizando o método .empty:\n{np.empty([14])}\n')
print(f'criação de array numpy utilizando o método .zeros:\n{np.zeros([12])}\n')
print(f'criação de array numpy utilizando o método .arange:\n{np.arange(101)}\n')
print(f'criação de array numpy utilizando o método .linspace:\n{np.linspace(0,40,num = 41)}\n')


criação de array numpy utilizando o método .array:
[0 1 2 3 4 5 6 7 8 9]

criação de array numpy utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

criação de array numpy utilizando o método .empty:
[ 0.   0.1  0.  -0.1  0.8 -0.1  0.8 -0.3  1.   0.   0.8  0.3  0.8  0.1]

criação de array numpy utilizando o método .zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

criação de array numpy utilizando o método .arange:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]

criação de array numpy utilizando o método .linspace:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 2

# NUMPY - 4° A importância de se definir o tipo de dado

In [33]:
import numpy as np

num_elementos = 100000000
array_performace = np.zeros(num_elementos, dtype = np.int32)

# NUMPY - 5° Criação de números randômicos

In [37]:
import numpy as np

rng = np.random.default_rng()
print(rng.random(10))

[0.91336166 0.57713292 0.52775235 0.01749693 0.84851609 0.27657651
 0.57618198 0.11165931 0.43524775 0.90971013]


# NUMPY - 6° Vetor, Matriz, Tensor

In [40]:
import numpy as np

rng = np.random.default_rng()
vetor = rng.random(3)
print(f'array de 1 dimensão (VETOR) randômico: \n{vetor}\n')
matriz = rng.random([3,3])
print(f'array de 2 dimensão (MATRIZ) randômico: \n{matriz}\n')
tensor = rng.random([3,3,3,3])
print(f'array de 3 dimensão (TENSOR) randômico: \n{tensor}\n')

array de 1 dimensão (VETOR) randômico: 
[0.42250985 0.75530902 0.94607036]

array de 2 dimensão (MATRIZ) randômico: 
[[0.20459499 0.10879479 0.67691814]
 [0.61939935 0.88460104 0.6499598 ]
 [0.01283528 0.52752521 0.18694153]]

array de 3 dimensão (TENSOR) randômico: 
[[[[0.20143989 0.75660636 0.72674852]
   [0.29648378 0.82729338 0.11950399]
   [0.35071169 0.77124562 0.58187945]]

  [[0.77721298 0.22490206 0.68752701]
   [0.62243177 0.53755061 0.75918971]
   [0.22198873 0.20834224 0.15941086]]

  [[0.72796263 0.91516411 0.23489485]
   [0.67101197 0.01473956 0.14387672]
   [0.71675149 0.3854855  0.15233517]]]


 [[[0.28368914 0.47755081 0.18028915]
   [0.24854263 0.93298156 0.0287928 ]
   [0.90651776 0.20289337 0.32275835]]

  [[0.32125706 0.69172933 0.50743234]
   [0.75791114 0.8724112  0.59349092]
   [0.45413031 0.16199403 0.59114867]]

  [[0.2674967  0.57962884 0.42886136]
   [0.19865125 0.76868086 0.97218128]
   [0.4599669  0.58888573 0.3301052 ]]]


 [[[0.12889143 0.01347845 0.7073

# NUMPY - 7° Ordenação e Adicionar elementos

In [55]:
import numpy as np

rng = np.random.default_rng()

array_1 = rng.random([2,3])
print(f'array 1 sem ordenação:\n{array_1}\n')
print(f'array 1 com ordenação:\n{np.sort(array_1, axis = 1)}\n')

# Concatenação
array_2 = rng.random([2,1])
print(f'Array 2:\n{array_2}\n')

array_concatenado = np.concatenate([array_1, array_2], axis=1)
print(f'Array concatenado:\n{array_concatenado}\n')

array_concatenado_2 = np.hstack([array_1,array_2])
print(f'Array Concatenado:\n{array_concatenado_2}\n')

array 1 sem ordenação:
[[0.21540762 0.863882   0.50445925]
 [0.93587395 0.9762544  0.6081694 ]]

array 1 com ordenação:
[[0.21540762 0.50445925 0.863882  ]
 [0.6081694  0.93587395 0.9762544 ]]

Array 2:
[[0.78342399]
 [0.0067512 ]]

Array concatenado:
[[0.21540762 0.863882   0.50445925 0.78342399]
 [0.93587395 0.9762544  0.6081694  0.0067512 ]]

Array Concatenado:
[[0.21540762 0.863882   0.50445925 0.78342399]
 [0.93587395 0.9762544  0.6081694  0.0067512 ]]



# Numpy - 8° Conhecendo o seu array

In [60]:
import numpy as np

rng = np.random.default_rng()
array_teste_4 = rng.random([22,40,15])
print(array_teste_4)

print(f'Quais são as suas dimensões:\n{array_teste_4.ndim}')
print(f'Qual seu formato:\n{array_teste_4.shape}')
print(f'Quantos elementos possui:\n{array_teste_4.size}')

[[[2.41863065e-01 1.27563558e-01 8.62175713e-01 ... 3.47011112e-01
   7.89075660e-01 7.30271233e-01]
  [8.54267179e-01 7.59916866e-01 7.05161635e-01 ... 7.24481280e-01
   5.76284292e-01 2.12493536e-01]
  [7.05258352e-01 3.51775920e-01 6.72113251e-01 ... 9.33799041e-01
   7.90302001e-01 3.32045482e-01]
  ...
  [3.84785482e-01 7.61633726e-01 2.21579713e-01 ... 1.10433365e-01
   1.84614772e-01 7.34835810e-01]
  [6.96439265e-01 8.23603738e-01 7.96294902e-01 ... 5.49835203e-01
   4.88167176e-01 1.41522128e-01]
  [4.49045196e-01 9.41794980e-01 9.11929109e-02 ... 2.22740770e-01
   2.05777228e-01 6.71742471e-01]]

 [[7.90969070e-01 7.26309194e-01 9.45306956e-01 ... 2.30946811e-01
   4.18763943e-01 2.08078659e-01]
  [5.00720497e-01 3.38993850e-01 9.64418859e-01 ... 2.25152002e-01
   6.24043081e-03 1.70386138e-03]
  [5.39898406e-01 8.61730928e-01 7.97250350e-01 ... 6.31036629e-01
   3.18493315e-01 8.88473164e-01]
  ...
  [3.75201754e-01 4.70828378e-01 5.91779735e-02 ... 7.39879273e-01
   6.88856

# Numpy - 9° Como mudar um formato de array

In [76]:
import numpy as np

array_a =np.arange(0,20)
print(f'Array a:\n{array_a}\n')
array_a = array_a.reshape(4,5)
print(f'Array a:\n{array_a}\n')

array_a = np.reshape(array_a, [4,5])
print(f'Array a:\n{array_a}\n')

array_a = array_a.flatten()
print(f'Array a:\n{array_a}\n')

array_b = array_a.reshape(4,5)
print(f'Array b:\n{array_b}\n')

array_b = np.vsplit(array_b,4)
print(f'Array b:\n{array_b}\n')
print(array_b[0])

Array a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array b:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array b:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]

[[0 1 2 3 4]]


# PLOTLY - 1° Abrir documentação

# PLOTLY - 2° Criando arrays para montar

In [83]:
import numpy as np

a = 3/4
b = 2/4
c = 1/4
vetor_a = np.ones(20)
vetor_b = np.ones(20)
vetor_c = np.ones(20)

for i in range(1,20):
  vetor_a[i] = vetor_a[i-1]+ a**i
  vetor_b[i] = vetor_b[i-1]+ b**i
  vetor_c[i] = vetor_c[i-1]+ c**i

  print(vetor_a)
  print(vetor_b)
  print(vetor_c)

  np.savetxt('vetor_a.txt', vetor_a, fmt ='%f', delimiter=';')
  np.savetxt('vetor_b.txt', vetor_b, fmt ='%f', delimiter=';')
  np.savetxt('vetor_c.txt', vetor_c, fmt ='%f', delimiter=';')

[1.   1.75 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.  ]
[1.  1.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1. ]
[1.   1.25 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.  ]
[1.     1.75   2.3125 1.     1.     1.     1.     1.     1.     1.
 1.     1.     1.     1.     1.     1.     1.     1.     1.     1.    ]
[1.   1.5  1.75 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.  ]
[1.     1.25   1.3125 1.     1.     1.     1.     1.     1.     1.
 1.     1.     1.     1.     1.     1.     1.     1.     1.     1.    ]
[1.       1.75     2.3125   2.734375 1.       1.       1.       1.
 1.       1.       1.       1.       1.       1.       1.       1.
 1.       1.       1.       1.      ]
[1.    1.5   1.75  1.875 1.    1.    1.    1.    1.    1.    1.    1.
 1.    1.    1.    1.    1.    1.    1.    1.   ]
[1.       1.25     1.3125   1.328125 1.      

# PLOTLY - 3° Criando nosso primeiro gráfico

In [84]:
import numpy as np
import plotly.express as px

array_a = np.loadtxt('vetor_a.txt', dtype = np.float64, delimiter =";")
array_b = np.loadtxt('vetor_b.txt', dtype = np.float64, delimiter =";")
array_c = np.loadtxt('vetor_c.txt', dtype = np.float64, delimiter =";")
print(array_a)

array_abc =np.vstack([array_a,array_b,array_c])
print(array_abc)
array_abc = array_abc.transpose()
print(array_abc)
fig = px.scatter(array_abc)
fig.show()

[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
 3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
 3.969932 3.977449 3.983087 3.987315]
[[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
  3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
  3.969932 3.977449 3.983087 3.987315]
 [1.       1.5      1.75     1.875    1.9375   1.96875  1.984375 1.992188
  1.996094 1.998047 1.999023 1.999512 1.999756 1.999878 1.999939 1.999969
  1.999985 1.999992 1.999996 1.999998]
 [1.       1.25     1.3125   1.328125 1.332031 1.333008 1.333252 1.333313
  1.333328 1.333332 1.333333 1.333333 1.333333 1.333333 1.333333 1.333333
  1.333333 1.333333 1.333333 1.333333]]
[[1.       1.       1.      ]
 [1.75     1.5      1.25    ]
 [2.3125   1.75     1.3125  ]
 [2.734375 1.875    1.328125]
 [3.050781 1.9375   1.332031]
 [3.288086 1.96875  1.333008]
 [3.466064 1.984375 1.333252]
 [3.599548 1.992188 1.333313]
 [3.699661 1.996